# Generated by Django 4.1.7 on 2023-04-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('national_code', models.IntegerField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(blank=True, choices=[('1', 'ترجیح میدهم اعلام نکنم'), ('2', 'مجرد'), ('3', 'متاهل')], max_length=10, null=True)),
                ('whatsapp_number', models.IntegerField()),
                ('cellphone_number', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('emergency_phone_number', models.IntegerField()),
                ('pragnancy', models.CharField(choices=[('1', 'باردار نیستم'), ('2', 'باردارم')], max_length=20)),
                ('taking_medication', models.BooleanField()),
                ('list_of_medication', models.CharField(max_length=250)),
                ('disease_background', models.CharField(blank=True, max_length=256, null=True)),
                ('disease_discribtion', models.CharField(blank=True, max_length=256, null=True)),
                ('orientation', models.CharField(choices=[('1', 'سایت'), ('2', 'اینستاگرام'), ('3', 'تلگرام'), ('4', 'واتساپ'), ('5', 'مربیان'), ('6', 'مسئولین موسسه'), ('7', 'دوره پاکسازی درون'), ('8', 'دوستان و آشنایان')], max_length=20)),
                ('course_price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Course Price')),
                ('deposit_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('issue_tracking', models.DecimalField(decimal_places=0, max_digits=6)),
                ('last_four_digits', models.DecimalField(decimal_places=0, max_digits=4)),
                ('deposit_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.class', verbose_name='Course')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='information.coach'),
        ),
    ]
