# Generated by Django 4.1.7 on 2023-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='any_discribtion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
