# Generated by Django 4.1.7 on 2023-04-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_usermodel_any_discribtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='course_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Course Price'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='emergency_phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='whatsapp_number',
            field=models.CharField(max_length=11),
        ),
    ]
