# Generated by Django 4.1.7 on 2023-04-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_class_price_alter_usermodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='taking_medication',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
