# Generated by Django 4.1.7 on 2023-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_usermodel_taking_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='list_of_medication',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
